using System;
using System.Collections.Generic;

#nullable disable

namespace TCC_WebAPI.Models
{
    public partial class Reta01
    {
        public int? A0000 { get; set; }
        public string A0100 { get; set; }
        public string B0110 { get; set; }
        public string E01a1 { get; set; }
        public DateTime? A0111 { get; set; }
        public DateTime? A0141 { get; set; }
        public string A0107 { get; set; }
        public string A0177 { get; set; }
        public string A0114 { get; set; }
        public string A0117 { get; set; }
        public string A0121 { get; set; }
        public string A01z0 { get; set; }
        public string C0181 { get; set; }
        public string A0171 { get; set; }
        public string CreateUserName { get; set; }
        public DateTime? CreateTime { get; set; }
        public string ModUserName { get; set; }
        public DateTime? ModTime { get; set; }
        public DateTime? ModTime1 { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string State { get; set; }
        public string C01tc { get; set; }
        public string C01wc { get; set; }
        public string C01xc { get; set; }
        public string C01yc { get; set; }
        public string C01zc { get; set; }
        public DateTime? C01zd { get; set; }
        public string C01ze { get; set; }
        public string C01vc { get; set; }
        public string C01zi { get; set; }
        public DateTime? C01zk { get; set; }
        public string C01zm { get; set; }
        public DateTime? C01zn { get; set; }
        public string C01zo { get; set; }
        public string C01zp { get; set; }
        public DateTime? C01zq { get; set; }
        public string C01zs { get; set; }
        public string E0122 { get; set; }
        public DateTime? A0144 { get; set; }
        public string E0116 { get; set; }
        public int? C0101 { get; set; }
        public int? A0151 { get; set; }
        public string C01zz { get; set; }
        public string Groups { get; set; }
        public string C0102 { get; set; }
        public string C0103 { get; set; }
        public string C0108 { get; set; }
        public string C0109 { get; set; }
        public string A0127 { get; set; }
        public string C010b { get; set; }
        public string C010c { get; set; }
        public string C010d { get; set; }
        public string C010e { get; set; }
        public DateTime? C0183 { get; set; }
        public string C010f { get; set; }
        public string C010h { get; set; }
        public string C010i { get; set; }
        public string C010l { get; set; }
        public string A0124 { get; set; }
        public DateTime? C0184 { get; set; }
        public string C0110 { get; set; }
        public string C010o { get; set; }
        public string C011a { get; set; }
        public string A0164 { get; set; }
        public string C010r { get; set; }
        public DateTime? C010s { get; set; }
        public DateTime? C010t { get; set; }
        public DateTime? C010x { get; set; }
        public string A0131 { get; set; }
        public string C010u { get; set; }
        public DateTime? C010v { get; set; }
        public DateTime? C01zu { get; set; }
        public string C0118 { get; set; }
        public string C0119 { get; set; }
        public string C011e { get; set; }
        public string A0101 { get; set; }
        public string C011g { get; set; }
        public string C011h { get; set; }
        public string C011i { get; set; }
        public string C011j { get; set; }
        public string A0174 { get; set; }
        public string C011k { get; set; }
        public DateTime? C011l { get; set; }
        public string C011m { get; set; }
        public string C011o { get; set; }
        public string C011u { get; set; }
        public string C011p { get; set; }
        public string C011q { get; set; }
        public string C011r { get; set; }
        public string C011t { get; set; }
        public string A0154 { get; set; }
        public string A0104 { get; set; }
        public string Guidkey { get; set; }
        public string C011v { get; set; }
        public string C011w { get; set; }
        public string C011n { get; set; }
        public string C011x { get; set; }
        public decimal? C011y { get; set; }
        public string E0102 { get; set; }
        public int? C011z { get; set; }
        public string C0120 { get; set; }
        public string C0122 { get; set; }
        public string A0181 { get; set; }
        public string C0121 { get; set; }
        public string C0123 { get; set; }
        public string C0125 { get; set; }
        public string C0126 { get; set; }
        public string Ccccc { get; set; }
        public string Cdddd { get; set; }
        public string C0127 { get; set; }
        public string C0128 { get; set; }
        public string C0129 { get; set; }
        public string C012a { get; set; }
        public string C012b { get; set; }
        public string C012c { get; set; }
        public string C012d { get; set; }
        public string C012e { get; set; }
        public string C012f { get; set; }
        public string C012g { get; set; }
        public string C012h { get; set; }
        public string C012i { get; set; }
        public string C012j { get; set; }
        public string C012k { get; set; }
        public string C012l { get; set; }
        public string C012m { get; set; }
        public string C012n { get; set; }
    }
}
