using System;
using System.Collections.Generic;

#nullable disable

namespace TCC_WebAPI.Models
{
    public partial class TccBusinessTrip
    {
        public int Id { get; set; }
        public string ProcessName { get; set; }
        public int? Incident { get; set; }
        public int? ProcessStatus { get; set; }
        public string RequestLoginName { get; set; }
        public string RequestUserIdentity { get; set; }
        public string RequestRealName { get; set; }
        public string RequestUserPost { get; set; }
        public string RequestDeptCode { get; set; }
        public string RequestDeptName { get; set; }
        public DateTime RequestDate { get; set; }
        public string FormNumber { get; set; }
        public string CardNo { get; set; }
        public string TravelType { get; set; }
        public string TaskTarget { get; set; }
        public string InviteUnit { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public DateTime? TravelBeginDate { get; set; }
        public DateTime? TravelEndDate { get; set; }
        public int? TotalDays { get; set; }
        public int? TotalHours { get; set; }
        public int? TotalMinutes { get; set; }
        public string FromCity { get; set; }
        public string TravelPersonsLoginName { get; set; }
        public string TravelPersons { get; set; }
        public string TravelPersonsIdcardNo { get; set; }
        public string TravelPersonsPosts { get; set; }
        public int? PersonTotal { get; set; }
        public int? PersonCount { get; set; }
        public int? ToDomesticOversea { get; set; }
        public string ToCountry { get; set; }
        public string ToCity { get; set; }
        public string ToDomain { get; set; }
        public string Vehicle { get; set; }
        public string Remark { get; set; }
        public DateTime? ProcessFinishDate { get; set; }
        public decimal? ExpenseMoney { get; set; }
        public int? AttachmentNum { get; set; }
        public string Source { get; set; }
        public string IsBeyond { get; set; }
        public string IsBorrowMoney { get; set; }
        public string Location { get; set; }
        public int? HaveBorrow { get; set; }
        public string HaveBorrowText { get; set; }
        public string PayType { get; set; }
        public string PaymentType { get; set; }
        public decimal? NoRepayMentAmount { get; set; }
        public string Currency { get; set; }
        public string CurrencyType { get; set; }
        public decimal? MoneyYb { get; set; }
        public decimal? Rate { get; set; }
        public decimal? BorrowMoneySmall { get; set; }
        public string BorrowMoneyBig { get; set; }
        public string Reject { get; set; }
        public string FPayMentType { get; set; }
        public decimal? FPayMoney { get; set; }
        public DateTime? FPayDate { get; set; }
        public string FAccountSubject { get; set; }
        public string FAccountSubjectName { get; set; }
        public string FPayBankCode { get; set; }
        public string FPayBankName { get; set; }
        public string FCheque { get; set; }
        public string FTransactor { get; set; }
        public int? IsLink { get; set; }
        public int? IsAccount { get; set; }
        public string BussinessCard { get; set; }
        public string ConfirmFinaceName { get; set; }
        public string ConfirmFinaceLoginName { get; set; }
        public string ConfirmFinaceUserIdentity { get; set; }
        public string ConfirmStatus { get; set; }
        public DateTime? ConfirmFinaceDate { get; set; }
        public int? Voucherid { get; set; }
        public string AuditAccountName { get; set; }
        public string AuditAccountLoginName { get; set; }
        public string AuditAccountUserIdentity { get; set; }
        public int? BusinessObject { get; set; }
        public decimal? Quota { get; set; }
        public string CurrencySubjectCode { get; set; }
        public string IsAbort { get; set; }
        public string BeyondSeats { get; set; }
        public string NeedAskForLeave { get; set; }
        public string AskForLeaveLoginName { get; set; }
        public string AskForLeaveRealName { get; set; }
        public string AskForLeaveIdentity { get; set; }
        public DateTime? AskForLeaveDate { get; set; }
        public string DeptCodeOfFeiyong { get; set; }
        public string DeptNameOfFeiyong { get; set; }
        public string VisaUserPost { get; set; }
        public string VisaRealName { get; set; }
        public string VisaLoginName { get; set; }
        public string VisaUserIdentity { get; set; }
        public string VisaDeptCode { get; set; }
        public string VisaDeptName { get; set; }
        public string VisaUserPost1 { get; set; }
        public int? Agency { get; set; }
        public int? Flag { get; set; }
        public decimal? PaymentAmountLowercaseShow { get; set; }
        public string PaymentAmountUppercase { get; set; }
        public decimal? PaymentExchangeShow { get; set; }
        public decimal? PaymentChangeLocalCurrencyAmountShow { get; set; }
        public string FinanceCurrencyText { get; set; }
        public DateTime? PaymentContractPaymentDate { get; set; }
        public int? AttachmentShow { get; set; }
        public string PaymentReceivingCompanyCode { get; set; }
        public string PaymentReceivingCompanyName { get; set; }
        public string PaymentBankAccount { get; set; }
        public string PaymentReceivingCompanyAddress { get; set; }
        public string PaymentBankName { get; set; }
        public string PaymentLineNumbers { get; set; }
        public string PaymentBankAddress { get; set; }
        public string PaymentDescription { get; set; }
        public int? BillFlag { get; set; }
        public string InvoiceCategoryText { get; set; }
        public int? InvoiceCategoryValue { get; set; }
        public string PaymentCommercialInvoiceCode { get; set; }
        public string InvoicesUnitName { get; set; }
        public int? IsReimbursed { get; set; }
        public int? PaymentMethodCode { get; set; }
        public string PaymentMethod { get; set; }
        public int? OnlyOne { get; set; }
        public string AllowForReimburse { get; set; }
        public int? ProjectByBranch { get; set; }
        public string ProjectOwnership { get; set; }
        public string ShenPiDanFormNumber { get; set; }
        public int? ShenPiDanId { get; set; }
        public string IsTianjinRegion { get; set; }
        public string IsTjSideTravel { get; set; }
        public int? StandrdType { get; set; }
    }
}
