using System;
using System.Collections.Generic;

#nullable disable

namespace TCC_WebAPI.Models
{
    public partial class TccHrmLyapplyDetailNewPerson
    {
        public int Id { get; set; }
        public string LyPersonStatus { get; set; }
        public string LyFormNumber { get; set; }
        public string LyStyle { get; set; }
        public string LyStyleId { get; set; }
        public string LyDept { get; set; }
        public string LyDeptId { get; set; }
        public string LyPersonName { get; set; }
        public string LySex { get; set; }
        public string LySexId { get; set; }
        public string LyAge { get; set; }
        public string LyDegree { get; set; }
        public string LyDegreeId { get; set; }
        public string LySchool { get; set; }
        public string LyMajor { get; set; }
        public string LyProjectNo { get; set; }
        public string LyProjectName { get; set; }
        public string LyPosation { get; set; }
        public string LyNation { get; set; }
        public string LyNationId { get; set; }
        public string LyCountry { get; set; }
        public string LyCountryId { get; set; }
        public string LyBirthday { get; set; }
        public string LyIdcardNo { get; set; }
        public string LyPoliticStyle { get; set; }
        public string LyReligiousBelief { get; set; }
        public string LyDiploma { get; set; }
        public string LyDiplomaId { get; set; }
        public string LyEduYear { get; set; }
        public string LyEduYearId { get; set; }
        public string LyGraduateTime { get; set; }
        public string LyStudyAbroadCountry { get; set; }
        public string LyStudyAbroadCountryId { get; set; }
        public string LyLanguage { get; set; }
        public string LyLanguageId { get; set; }
        public string LyLanguageLevel { get; set; }
        public string LyLanguageLevelId { get; set; }
        public string LyLanguageScore { get; set; }
        public string LyConcractDeadline { get; set; }
        public string LyConcractDeadlineId { get; set; }
        public string LySendToPlace { get; set; }
        public string LySendToPlaceId { get; set; }
        public string LyManageType { get; set; }
        public string LyManageTypeId { get; set; }
        public string LyPosationKind { get; set; }
        public string LyPosationKindId { get; set; }
        public string LyPosationName { get; set; }
        public string LyPosationNameId { get; set; }
        public string LyWageLevel { get; set; }
        public string LyWageLevelId { get; set; }
        public string LyWageStandard { get; set; }
        public string LyWageContent { get; set; }
        public string LyWageGetPlace { get; set; }
        public string LyWageGetPlaceId { get; set; }
        public string LyWageBelong { get; set; }
        public string LyInsureBelong { get; set; }
        public string LyBonusSendFlag { get; set; }
        public string LyPhone { get; set; }
        public string LyBeginWorkDate { get; set; }
        public string LyLastWorkCompany { get; set; }
        public string LyTitles { get; set; }
        public string LyCompetency { get; set; }
        public string LyWorkYears { get; set; }
        public string LyContractType { get; set; }
        public string LyContractTypeId { get; set; }
        public string LyProbation { get; set; }
        public string LyProbationId { get; set; }
        public string LyComeDate { get; set; }
        public string LyCompetencyName { get; set; }
        public string AttFileId { get; set; }
        public string RzComeinDate { get; set; }
        public string RzSendFlag { get; set; }
        public string RzSendFlagId { get; set; }
        public string RzHasBx { get; set; }
        public string RzHasBxid { get; set; }
        public string RzJg { get; set; }
        public string RzJgid { get; set; }
        public string RzSyd { get; set; }
        public string RzSydid { get; set; }
        public string RzXhkszd { get; set; }
        public string RzXhkszdid { get; set; }
        public string RzCsd { get; set; }
        public string RzCsdid { get; set; }
        public string RzIdcardOverDate { get; set; }
        public string RzIdcardLastTime { get; set; }
        public string RzIdcardLastTimeId { get; set; }
        public string RzPosationUpTime { get; set; }
        public string RzPosationLevel { get; set; }
        public string RzPosationLevelId { get; set; }
        public string RzPosationXs { get; set; }
        public string RzChangeFlag { get; set; }
        public string RzChangeFlagId { get; set; }
        public string RzChangeTime { get; set; }
        public string RzBxhdjs { get; set; }
        public string RzGjjhdjs { get; set; }
        public string RzBxjfdd { get; set; }
        public string RzBxjfddid { get; set; }
        public string RzGjjjfdd { get; set; }
        public string RzGjjjfddid { get; set; }
        public string RzChangeGdgz { get; set; }
        public string RzChangeGwjt { get; set; }
        public string RzDomanName { get; set; }
        public string RzDomanPassWord { get; set; }
        public string RzEmail { get; set; }
        public string RzEmailPassWord { get; set; }
        public string LyDomainUser { get; set; }
        public string LyWageStyle { get; set; }
        public string RzMajor { get; set; }
        public string RzMajorId { get; set; }
        public string RzZz { get; set; }
        public string RzZzid { get; set; }
        public string RzSpecicalZz { get; set; }
        public string RzDeptGroup { get; set; }
        public string RzDeptGroupId { get; set; }
        public string RzMaster { get; set; }
        public string RzMasterId { get; set; }
        public string RzHasZz { get; set; }
        public string RzHasNotice { get; set; }
        public string LyOtherAgree { get; set; }
        public string LyOtherAgreeContent { get; set; }
    }
}
