using System;
using System.Collections.Generic;

#nullable disable

namespace TCC_WebAPI.Models
{
    public partial class TccInvoicesReceived
    {
        public int Id { get; set; }
        public string ProcessName { get; set; }
        public int? Incident { get; set; }
        public string RequestLoginName { get; set; }
        public string RequestRealName { get; set; }
        public string RequestIdentity { get; set; }
        public string RequestDeptCode { get; set; }
        public string RequestDeptName { get; set; }
        public DateTime? RequestDate { get; set; }
        public string FormNumber { get; set; }
        public int? ProcessStatus { get; set; }
        public DateTime? ProcessFinishDate { get; set; }
        public string RequestTelephone { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public decimal? ProjectSchedule { get; set; }
        public string ProjectCategory { get; set; }
        public string ContractCode { get; set; }
        public string ContractName { get; set; }
        public string ContractCategory { get; set; }
        public string ContractForm { get; set; }
        public decimal? ContractAmount { get; set; }
        public decimal? ContractPaymentAmount { get; set; }
        public decimal? ContractPaymentPercentage { get; set; }
        public string SupplierCode { get; set; }
        public string SupplierName { get; set; }
        public decimal? AggregateRecInvoiceAmount { get; set; }
        public decimal? AggregateRecReceiptAmount { get; set; }
        public decimal? AggregateWithholdingTax { get; set; }
        public string InvoiceCategoryValue { get; set; }
        public string InvoiceCategoryText { get; set; }
        public decimal? InvoiceTotalAmount { get; set; }
        public DateTime? InvoiceDate { get; set; }
        public string InvoiceContent { get; set; }
        public decimal? InvoiceTaxAmount { get; set; }
        public decimal? TaxRate { get; set; }
        public decimal? SingleInvoiceAmount { get; set; }
        public string BillBeginCode { get; set; }
        public int? Number { get; set; }
        public string FinaceTicketUserLoginName { get; set; }
        public string FinaceTicketUserRealName { get; set; }
        public string FinaceTicketUserIdentity { get; set; }
        public DateTime? FinaceTicketDate { get; set; }
        public int? FinaceInvoiceNumber { get; set; }
        public decimal? FinaceTotalAmount { get; set; }
        public decimal? FinaceTotalTaxAmount { get; set; }
        public decimal? FinaceTotalWithholdingTax { get; set; }
        public decimal? FinaceTotalRefundedTax { get; set; }
        public string ConfirmLoginName { get; set; }
        public string ConfirmRealName { get; set; }
        public string ConfirmIdentity { get; set; }
        public DateTime? ConfirmDate { get; set; }
        public string PaymentCategory { get; set; }
        public string ContractCurrency { get; set; }
        public int? IsDrawback { get; set; }
        public decimal? TotelReturnTax { get; set; }
        public decimal? PaymentCanReturnTaxAmount { get; set; }
        public decimal? PaymentApplyReturnTaxAmount { get; set; }
        public decimal? PaymentExchange { get; set; }
        public decimal? PaymentChangeLocalCurrencyAmount { get; set; }
        public string PaymentCurrency { get; set; }
        public string PaymentReceivingCompanyName { get; set; }
        public string PaymentReceivingCompanyCode { get; set; }
        public string PaymentBankAccount { get; set; }
        public string PaymentReceivingCompanyAddress { get; set; }
        public string PaymentBankName { get; set; }
        public string PaymentLineNumbers { get; set; }
        public string PaymentBankAddress { get; set; }
        public string PaymentSwiftCode { get; set; }
        public string PaymentIbanCode { get; set; }
        public string PaymentAbacode { get; set; }
        public string SubjectCode { get; set; }
        public string FinancePaymentBank { get; set; }
        public string FinancePaymentBankAccount { get; set; }
        public int? VoucherId { get; set; }
        public string VoucherCode { get; set; }
        public int? TaxVoucherId { get; set; }
        public string TaxVoucherCode { get; set; }
        public int? IsVoucher { get; set; }
        public string RelevanceInvoiceCategoryValue { get; set; }
        public string RelevanceInvoiceCategoryText { get; set; }
        public string CasierClaimUserName { get; set; }
        public string CasierClaimLoginUserName { get; set; }
        public DateTime? CasierClaimDate { get; set; }
        public string AccountingAuditUserName { get; set; }
        public string AccountingAuditLoginUserName { get; set; }
        public DateTime? AccountingAuditDate { get; set; }
        public int? Attachment { get; set; }
        public int? TaxAttachment { get; set; }
        public string UnitJnw { get; set; }
        public int? IsTs { get; set; }
        public int? GoodClass { get; set; }
        public string UnitCode { get; set; }
        public string UnitName { get; set; }
        public string InvoicesUnitName { get; set; }
        public string SignCode { get; set; }
        public string SignName { get; set; }
        public decimal? TotalTaxAmount { get; set; }
        public decimal? TaxAmount { get; set; }
        public string ProjectJnw { get; set; }
        public decimal? SurplusReturnTax { get; set; }
        public decimal? InvoiceTotalBillAmount { get; set; }
        public int? BillStatus { get; set; }
        public decimal? TaxAmountRate { get; set; }
        public string ProjectCodeDev { get; set; }
        public string VoucherDeptCode { get; set; }
        public string VoucherDeptName { get; set; }
        public int? RequestType { get; set; }
        public string ApplicationName { get; set; }
        public int? ApplicationCode { get; set; }
        public decimal? InvoiceTotalAmountRmb { get; set; }
        public decimal? InvoiceTotalBillAmountRmb { get; set; }
        public decimal? TotalTaxAmountRmb { get; set; }
        public string OtherSubjectCode { get; set; }
        public string OtherSubjectName { get; set; }
        public int? TsVoucherId { get; set; }
        public string TsVoucherCode { get; set; }
        public string OffSingleNumber { get; set; }
        public decimal? TotalPrice { get; set; }
        public decimal? MoneyRate { get; set; }
        public int? HistoryInvoiceCategoryValue { get; set; }
        public string FinanceDraftMode { get; set; }
        public decimal? FinanceDraftTotal { get; set; }
        public decimal? FinancePaymentAmount { get; set; }
        public decimal? FinanceDraftAmount { get; set; }
        public int? IsForeign { get; set; }
        public string VoucherBillTaxCurrency { get; set; }
        public decimal? VoucherBillTaxAmount { get; set; }
        public decimal? VoucherBillTaxAmountRmb { get; set; }
        public string VoucherTaxCurrency { get; set; }
        public decimal? VoucherTaxExchange { get; set; }
        public decimal? VoucherTaxAmount { get; set; }
        public string AccountType { get; set; }
        public string RelevanceRateCode { get; set; }
        public string RelevanceRateText { get; set; }
        public string ReMark { get; set; }
        public string ProjectCategorySub { get; set; }
        public string ProjectCategoryInfo { get; set; }
        public decimal? BillAmountTotalCnt { get; set; }
        public decimal? BillTaxAmountTotalCnt { get; set; }
        public string BillConfirmUserLogin { get; set; }
        public string BillConfirmUserName { get; set; }
        public string FoundsUsedCode { get; set; }
        public string FoundsUsedName { get; set; }
    }
}
