using System;
using System.Collections.Generic;

#nullable disable

namespace TCC_WebAPI.Models
{
    public partial class TccPaymentProcessMultiple
    {
        public int Id { get; set; }
        public DateTime? RequestDate { get; set; }
        public DateTime? ProcessFinishDate { get; set; }
        public string ProcessName { get; set; }
        public int? Incident { get; set; }
        public int? ProcessStatus { get; set; }
        public string RequestLoginName { get; set; }
        public string RequestRealName { get; set; }
        public string RequestSfzh { get; set; }
        public string RequestDeptCode { get; set; }
        public string RequestDeptName { get; set; }
        public DateTime? RequestDate1 { get; set; }
        public string RequestFormNumber { get; set; }
        public int? RequestType { get; set; }
        public string RequestTypeName { get; set; }
        public int? RequestPayCategory { get; set; }
        public string RequestPayCategoryName { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public int? ProjectType { get; set; }
        public string ProjectCategory { get; set; }
        public string ProjectTypeName { get; set; }
        public decimal? ProjectContractAmount { get; set; }
        public decimal? ProjectReceivedAmount { get; set; }
        public decimal? ProjectReceivedPercentage { get; set; }
        public decimal? ProjectPaymentContractTotalAmount { get; set; }
        public decimal? ProjectPaymentAmount { get; set; }
        public decimal? ProjectAccountPayable { get; set; }
        public decimal? ProjectPojectProgressPercentage { get; set; }
        public decimal? ProjectProfitMargin { get; set; }
        public string ProjectManager { get; set; }
        public string ProjectManagerLoginName { get; set; }
        public string ProjectManagerIdentityId { get; set; }
        public int? PaymentMethod { get; set; }
        public string PaymentMethodName { get; set; }
        public decimal? PaymentAmountLowercase { get; set; }
        public string PaymentAmountUppercase { get; set; }
        public string PaymentCurrency { get; set; }
        public string PaymentReceivingCompanyCode { get; set; }
        public string PaymentReceivingCompanyName { get; set; }
        public string PaymentReceivingCompanyAddress { get; set; }
        public string PaymentBankAccount { get; set; }
        public DateTime? PaymentContractPaymentDate { get; set; }
        public DateTime? ExpectedRecoveryDate { get; set; }
        public string PaymentBankName { get; set; }
        public string PaymentLineNumbers { get; set; }
        public decimal? PaymentAmount { get; set; }
        public int? Attachment { get; set; }
        public int? PaymentFundMode { get; set; }
        public string PaymentFundModeName { get; set; }
        public decimal? PaymentExchange { get; set; }
        public decimal? PaymentChangeLocalCurrencyAmount { get; set; }
        public string PaymentSwiftCode { get; set; }
        public string PaymentIbanCode { get; set; }
        public string PaymentAbacode { get; set; }
        public string PaymentGuanDanCode { get; set; }
        public string PaymentGuanDanGoodsName { get; set; }
        public string PaymentGuanDanCurrency { get; set; }
        public string PaymentGuanDanTotal { get; set; }
        public string PaymentTransportationMode { get; set; }
        public string PaymentTransportationModeName { get; set; }
        public decimal? FinanceDraftTotal { get; set; }
        public string FinanceDraftMode { get; set; }
        public decimal? FinanceDraftEnabledAmount { get; set; }
        public decimal? FinanceDraftSurplusAmount { get; set; }
        public decimal? FinancePaymentTotal { get; set; }
        public decimal? FinanceDraftAmount { get; set; }
        public decimal? FinancePaymentAmount { get; set; }
        public string FinancePaymentBank { get; set; }
        public string FinancePaymentBankAccount { get; set; }
        public string FinanceSubjectCode { get; set; }
        public string FinanceSubjectName { get; set; }
        public decimal? FinanceExchange { get; set; }
        public decimal? FinanceChangeLocalCurrencyAmount { get; set; }
        public string FinanceCurrency { get; set; }
        public int? IsLock { get; set; }
        public string LockLoginUserName { get; set; }
        public string LockUserName { get; set; }
        public string CasierClaimUserName { get; set; }
        public string CasierClaimLoginUserName { get; set; }
        public string AccountingAuditUserName { get; set; }
        public string AccountingAuditLoginUserName { get; set; }
        public DateTime? AccountingAuditDate { get; set; }
        public string Approver1 { get; set; }
        public string Approver1LoginName { get; set; }
        public string Approver2 { get; set; }
        public string Approver2LoginName { get; set; }
        public int? Voucherid { get; set; }
        public string VoucherCode { get; set; }
        public string ContractUnitName { get; set; }
        public string ContractUnitCode { get; set; }
        public string PaymentBankAddress { get; set; }
        public string ProjectPaymentInfo { get; set; }
        public string RequestTelephone { get; set; }
        public decimal? ProjectManagementCost { get; set; }
        public decimal? ProjectNeiBuRenGongFei { get; set; }
        public int? IsFinanceHead { get; set; }
        public decimal? WithholdingTax { get; set; }
        public decimal? OtherCost { get; set; }
        public decimal? PaymentPayableAmount { get; set; }
        public decimal? PaymentWithholdingAmount { get; set; }
        public decimal? FinanceWithholdingTaxPercentage { get; set; }
        public decimal? PaymentOtherPaymentTotal { get; set; }
        public decimal? FinancePaymentDraftValidAmount { get; set; }
        public string CardNo { get; set; }
        public string CardName { get; set; }
        public string CardBank { get; set; }
        public string FinancePaymentItemSubjectCode { get; set; }
        public string FinancePaymentItemSubjectName { get; set; }
        public decimal? PaymentBillAmount { get; set; }
        public string FinancePaymentItemSubjectNameAccount { get; set; }
        public decimal? PaymentInputVat { get; set; }
        public decimal? FinanceWithHoldingInputVat { get; set; }
        public decimal? FinancePaymentTotalTotal { get; set; }
        public int? PaymentApplicationCode { get; set; }
        public string PaymentApplicationName { get; set; }
        public string PaymentVoucherDeptCode { get; set; }
        public string PaymentVoucherDeptName { get; set; }
        public string PaymentDescription { get; set; }
        public string PaymentReceiptCode { get; set; }
        public string PaymentCommercialInvoiceCode { get; set; }
        public DateTime? CasierClaimDate { get; set; }
        public string SignSupplierCode { get; set; }
        public string SignSupplierName { get; set; }
        public string ContractType { get; set; }
        public int? Subject2Type { get; set; }
        public int? IsProjectSingle { get; set; }
        public decimal? ContractExchange { get; set; }
        public decimal? PaymentTotal { get; set; }
        public decimal? PaymentAcutlCurrencyPaymentAmount { get; set; }
        public int? FinanceDecimalDigit { get; set; }
        public int? FinnaceCalculateMode { get; set; }
        public int? Location { get; set; }
        public string ContractUnitJnw { get; set; }
        public int? ProjectIsFinish { get; set; }
        public int? IsFile { get; set; }
        public decimal? TotalTaxBasic { get; set; }
        public string BuyForeignCurrency { get; set; }
        public decimal? BuyForeignAmount { get; set; }
        public decimal? BuyForeignExchange { get; set; }
        public decimal? BuyForeignHanderCharge { get; set; }
        public decimal? BuyForeignPostage { get; set; }
        public int? IsBuyForeign { get; set; }
        public string BuyForeignOperateLoginName { get; set; }
        public string BuyForeignOperateName { get; set; }
        public DateTime? BuyForeignOperateTime { get; set; }
        public int? IsAuditType { get; set; }
        public int? BillFlag { get; set; }
        public string InvoicesUnitName { get; set; }
        public string InvoiceCategoryText { get; set; }
        public int? InvoiceCategoryValue { get; set; }
        public decimal? InvoiceBillAmount { get; set; }
        public decimal? InvoiceTaxAmount { get; set; }
        public decimal? InvoiceTotalAmount { get; set; }
        public string ProjectJnw { get; set; }
        public decimal? PaymentWithoutInputVat { get; set; }
        public decimal? PaymentWithoutOtherTax { get; set; }
        public int? FinanceDecimalDigitForOther { get; set; }
        public int? FinnaceCalculateModeForOther { get; set; }
        public decimal? PaymentOtherExchange { get; set; }
        public string PaymentLinkFormNumber { get; set; }
        public int? PaymentProjectIsEpc { get; set; }
        public int? IsValidProject { get; set; }
        public int? PaymentSource { get; set; }
        public int? IsSupplierOrCustomer { get; set; }
        public int? RequestYear { get; set; }
        public int? RequestQuarter { get; set; }
        public int? RequestSourceType { get; set; }
        public string ProjectCodeDev { get; set; }
        public string PaymentVatcurrency { get; set; }
        public decimal? PaymentInputVatvoucher { get; set; }
        public decimal? PaymentWithoutInputVatvoucher { get; set; }
        public int? FinanceDecimalDigitForVat { get; set; }
        public int? FinnaceCalculateModeForVat { get; set; }
        public decimal? FineAmount { get; set; }
        public decimal? PaymentWithoutOtherTaxVoucher { get; set; }
        public decimal? ExchangeVoucher { get; set; }
        public string PeptjSid { get; set; }
        public decimal? PaymentTotalContractAmount { get; set; }
        public decimal? ExchangeRateDifference { get; set; }
        public decimal? Budget { get; set; }
        public decimal? BudgetHappenedAmount { get; set; }
        public decimal? BudgetHappeningAmount { get; set; }
        public decimal? BudgetRemainAmount { get; set; }
        public int? RunningCost { get; set; }
        public decimal? ProjectAdjustProcess { get; set; }
        public decimal? PaymentOtherAmount { get; set; }
        public decimal? PaymentAirlineTicketAmount { get; set; }
        public int? IsAdjustDept { get; set; }
        public string ProjectXmgs { get; set; }
        public decimal? ProjectBkapplyAmount { get; set; }
        public decimal? ProjectBkpaymentAmount { get; set; }
        public decimal? ProjectBktotal { get; set; }
        public string RequestSourceType2 { get; set; }
        public decimal? PaymentOtherBuyPaymentTotal { get; set; }
        public int? ProjectQqflag { get; set; }
        public int? ProjectQqlevel { get; set; }
        public int? RequestProjectType { get; set; }
        public int? IsForeign { get; set; }
        public int? IsTaxVoucher { get; set; }
        public int? FinanceLeaderFlag { get; set; }
        public int? IsHaveBill { get; set; }
        public int? ContractLawsuit { get; set; }
        public int? LawsuitStatus { get; set; }
        public int? PbillStatus { get; set; }
        public string Finalengineeringcost { get; set; }
        public int? IsRenderedBills { get; set; }
        public string RevolvingFundHoldName { get; set; }
        public string RevolvingFundHoldLogin { get; set; }
        public decimal? RevolvingFundBalance { get; set; }
        public int? IsAddNewPaymentInfo { get; set; }
        public string RequestItemType { get; set; }
        public decimal? DiffValue { get; set; }
        public decimal? BalanceValue { get; set; }
        public decimal? ProjectOtherCost { get; set; }
        public string BillConfirmUserLogin { get; set; }
        public string BillConfirmUserName { get; set; }
        public string FoundsUsedCode { get; set; }
        public string FoundsUsedName { get; set; }
    }
}
