using System;
using System.Collections.Generic;

#nullable disable

namespace TCC_WebAPI.Models
{
    public partial class ViewReportPaymentProcessMultiple
    {
        public int Id { get; set; }
        public string ProjectInfoBasic { get; set; }
        public DateTime? RequestDate { get; set; }
        public DateTime? ProcessFinishDate { get; set; }
        public string ProcessName { get; set; }
        public int? Incident { get; set; }
        public int? ProcessStatus { get; set; }
        public string RequestLoginName { get; set; }
        public string RequestRealName { get; set; }
        public string RequestSfzh { get; set; }
        public string RequestDeptCode { get; set; }
        public string RequestDeptName { get; set; }
        public string RequestDate1 { get; set; }
        public string RequestFormNumber { get; set; }
        public string VchrnumCode { get; set; }
        public int? RequestType { get; set; }
        public string RequestTypeName { get; set; }
        public int? RequestPayCategory { get; set; }
        public string RequestPayCategoryName { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public int? ProjectType { get; set; }
        public string ProjectCategory { get; set; }
        public string ProjectTypeName { get; set; }
        public string ProjectContractAmount { get; set; }
        public string ProjectReceivedAmount { get; set; }
        public string ProjectReceivedPercentage { get; set; }
        public string ProjectPaymentContractTotalAmount { get; set; }
        public string ProjectPaymentAmount { get; set; }
        public string ProjectAccountPayable { get; set; }
        public string ProjectPojectProgressPercentage { get; set; }
        public string ProjectProfitMargin { get; set; }
        public string ProjectManager { get; set; }
        public string ProjectManagerLoginName { get; set; }
        public string ProjectManagerIdentityId { get; set; }
        public int? PaymentMethod { get; set; }
        public string PaymentMethodName { get; set; }
        public string PaymentAmountLowercase { get; set; }
        public string PaymentAmountUppercase { get; set; }
        public string PaymentCurrency { get; set; }
        public string PaymentReceivingCompanyCode { get; set; }
        public string PaymentReceivingCompanyName { get; set; }
        public string PaymentReceivingCompanyAddress { get; set; }
        public string PaymentBankAccount { get; set; }
        public string PaymentContractPaymentDate { get; set; }
        public string PaymentBankName { get; set; }
        public string PaymentLineNumbers { get; set; }
        public string PaymentAmount { get; set; }
        public int? Attachment { get; set; }
        public int? PaymentFundMode { get; set; }
        public string PaymentFundModeName { get; set; }
        public string PaymentExchange { get; set; }
        public string PaymentChangeLocalCurrencyAmount { get; set; }
        public string PaymentSwiftCode { get; set; }
        public string PaymentIbanCode { get; set; }
        public string PaymentAbacode { get; set; }
        public string PaymentGuanDanCode { get; set; }
        public string PaymentGuanDanGoodsName { get; set; }
        public string PaymentGuanDanCurrency { get; set; }
        public string PaymentGuanDanTotal { get; set; }
        public string PaymentTransportationMode { get; set; }
        public string PaymentTransportationModeName { get; set; }
        public string FinanceDraftTotal { get; set; }
        public string FinanceDraftMode { get; set; }
        public string FinanceDraftEnabledAmount { get; set; }
        public string FinanceDraftSurplusAmount { get; set; }
        public string FinancePaymentTotal { get; set; }
        public string FinanceDraftAmount { get; set; }
        public string FinancePaymentAmount { get; set; }
        public string FinancePaymentBank { get; set; }
        public string FinancePaymentBankAccount { get; set; }
        public string FinanceSubjectCode { get; set; }
        public string FinanceSubjectName { get; set; }
        public string FinanceExchange { get; set; }
        public string FinanceChangeLocalCurrencyAmount { get; set; }
        public string FinanceCurrency { get; set; }
        public int? IsLock { get; set; }
        public string LockLoginUserName { get; set; }
        public string LockUserName { get; set; }
        public string CasierClaimUserName { get; set; }
        public string CasierClaimLoginUserName { get; set; }
        public string AccountingAuditUserName { get; set; }
        public string AccountingAuditLoginUserName { get; set; }
        public DateTime? AccountingAuditDate { get; set; }
        public string Approver1 { get; set; }
        public string Approver1LoginName { get; set; }
        public string Approver2 { get; set; }
        public string Approver2LoginName { get; set; }
        public int? Voucherid { get; set; }
        public string VoucherCode { get; set; }
        public string ContractUnitName { get; set; }
        public string ContractUnitCode { get; set; }
        public string PaymentBankAddress { get; set; }
        public string ProjectPaymentInfo { get; set; }
        public string RequestTelephone { get; set; }
        public string ProjectManagementCost { get; set; }
        public string ProjectNeiBuRenGongFei { get; set; }
        public int? IsFinanceHead { get; set; }
        public string WithholdingTax { get; set; }
        public string OtherCost { get; set; }
        public string PaymentPayableAmount { get; set; }
        public string PaymentWithholdingAmount { get; set; }
        public string FinanceWithholdingTaxPercentage { get; set; }
        public string PaymentOtherPaymentTotal { get; set; }
        public string FinancePaymentDraftValidAmount { get; set; }
        public string CardNo { get; set; }
        public string CardName { get; set; }
        public string CardBank { get; set; }
        public string FinancePaymentItemSubjectCode { get; set; }
        public string FinancePaymentItemSubjectName { get; set; }
        public string PaymentBillAmount { get; set; }
        public string FinancePaymentItemSubjectNameAccount { get; set; }
        public string PaymentInputVat { get; set; }
        public string FinanceWithHoldingInputVat { get; set; }
        public string FinancePaymentTotalTotal { get; set; }
        public int? PaymentApplicationCode { get; set; }
        public string PaymentApplicationName { get; set; }
        public string PaymentVoucherDeptCode { get; set; }
        public string PaymentVoucherDeptName { get; set; }
        public string PaymentDescription { get; set; }
        public string PaymentReceiptCode { get; set; }
        public string PaymentCommercialInvoiceCode { get; set; }
        public DateTime? CasierClaimDate { get; set; }
        public string SignSupplierCode { get; set; }
        public string SignSupplierName { get; set; }
        public string ContractType { get; set; }
        public int? Subject2Type { get; set; }
        public int? IsProjectSingle { get; set; }
        public string ContractExchange { get; set; }
        public string PaymentTotal { get; set; }
        public string PaymentAcutlCurrencyPaymentAmount { get; set; }
        public int? FinanceDecimalDigit { get; set; }
        public int? FinnaceCalculateMode { get; set; }
        public string Location { get; set; }
        public string ContractUnitJnw { get; set; }
        public int? ProjectIsFinish { get; set; }
        public int? IsFile { get; set; }
        public decimal? TotalTaxBasic { get; set; }
        public string BuyForeignCurrency { get; set; }
        public string BuyForeignAmount { get; set; }
        public string BuyForeignExchange { get; set; }
        public string BuyForeignHanderCharge { get; set; }
        public string BuyForeignPostage { get; set; }
        public int? IsBuyForeign { get; set; }
        public string BuyForeignOperateLoginName { get; set; }
        public string BuyForeignOperateName { get; set; }
        public DateTime? BuyForeignOperateTime { get; set; }
        public int? IsAuditType { get; set; }
        public string BillFlag { get; set; }
        public string InvoicesUnitName { get; set; }
        public string InvoiceCategoryText { get; set; }
        public int? InvoiceCategoryValue { get; set; }
        public string InvoiceBillAmount { get; set; }
        public string InvoiceTaxAmount { get; set; }
        public string InvoiceTotalAmount { get; set; }
        public string ProjectJnw { get; set; }
        public string PaymentWithoutInputVat { get; set; }
        public string PaymentWithoutOtherTax { get; set; }
        public int? FinanceDecimalDigitForOther { get; set; }
        public int? FinnaceCalculateModeForOther { get; set; }
        public string PaymentOtherExchange { get; set; }
        public string PaymentLinkFormNumber { get; set; }
        public int? PaymentProjectIsEpc { get; set; }
        public int? IsValidProject { get; set; }
        public int? PaymentSource { get; set; }
        public int? IsSupplierOrCustomer { get; set; }
        public int? RequestYear { get; set; }
        public int? RequestQuarter { get; set; }
        public int? RequestSourceType { get; set; }
        public string ProjectCodeDev { get; set; }
        public string PaymentVatcurrency { get; set; }
        public string PaymentInputVatvoucher { get; set; }
        public string PaymentWithoutInputVatvoucher { get; set; }
        public int? FinanceDecimalDigitForVat { get; set; }
        public int? FinnaceCalculateModeForVat { get; set; }
        public string FineAmount { get; set; }
        public string PaymentWithoutOtherTaxVoucher { get; set; }
        public string ExchangeVoucher { get; set; }
        public int? PeptjSid { get; set; }
        public string PaymentTotalContractAmount { get; set; }
        public string ExchangeRateDifference { get; set; }
        public string Budget { get; set; }
        public string BudgetHappenedAmount { get; set; }
        public string BudgetHappeningAmount { get; set; }
        public string BudgetRemainAmount { get; set; }
        public string RunningCost { get; set; }
        public decimal? ProjectAdjustProcess { get; set; }
        public string PaymentAirlineTicketAmount { get; set; }
        public string PaymentOtherAmount { get; set; }
        public string Skje { get; set; }
        public string Rmb { get; set; }
        public string Type { get; set; }
        public string Currency { get; set; }
        public string PayCmpName { get; set; }
        public string ProjectInfo { get; set; }
    }
}
